name: Build & Release Desktop App to GH

on: 
  workflow_call:
    inputs:
      APPINFO:
        required: true
        type: string

permissions:
  contents: write
  
concurrency:
  group: "deployment"
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
      matrix:
        os:
          [
            #{ name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            #{ name: 'macos', image: 'macos-latest' }
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Before Checkout Print
        run: echo ${{ github.action_path }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: After Checkout Print
        run: echo ${{ github.action_path }}
