name: Build & Release Desktop App to GH

on: 
  workflow_call:
    inputs:
      APPINFO:
        required: true
        type: string

permissions:
  contents: write
  
concurrency:
  group: "deployment"
  cancel-in-progress: true
  
jobs:
  build:
    strategy:
      matrix:
        os:
          [
            #{ name: 'linux', image: 'ubuntu-latest' },
            { name: 'windows', image: 'windows-latest' },
            #{ name: 'macos', image: 'macos-latest' }
          ]
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout repo
        if: ${{ matrix.os.name == 'windows'}}
        uses: actions/checkout@v4
        with:
          repository: VHP1946/VHP1946.github.io
          path: temp
          ref: 'main'
          sparse-checkout: |
            .github/workflows/forge.config.js
          sparse-checkout-cone-mode: false

      - run: |
          echo ${{ github.workspace }}
          cd main
          echo ${{ github.workspace }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: |
          npm ci
          npm install electron-packager --save-dev
          npm install @electron-forge/cli --save-dev
          npm install @electron-forge/maker-zip --save-dev
          npm install @electron-forge/maker-wix --save-dev
          npm install @electron-forge/maker-deb --save-dev
          npm install @electron-forge/plugin-auto-unpack-natives --save-dev
          npm install @electron-forge/plugin-fuses --save-dev
      
      - name: Add WiX toolkit to PATH
        if: ${{ matrix.os.name == 'windows'}}
        shell: bash
        run: |
          npm install electron-wix-msi --save-dev
          echo "${WIX}bin" >> $GITHUB_PATH
          cp ../temp/forge.config.js ./

      #- run: npm run make
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/make/**/*.*
          body_path: 'docs/CHANGELOG.md'
          tag_name: v${{ fromJson(inputs.APPINFO).version }}
