name: Package & Release vhp Module

on: 
  workflow_call:
    inputs:
      APPINFO:
        required: true
        type: string

permissions:
  contents: write
  
concurrency:
  group: "deployment"
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build'
        run: echo 'Hello'