name: Workflow Caller

on: workflow_call

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  get-info:
    name: Get App Info
    runs-on: ubuntu-latest
    outputs:
      APPINFO: ${{ steps.set-info.outputs.APPINFO }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: 'Load package.json'
        id: set-info
        run: |
          {  
            echo 'APPINFO<<EOF'
            cat ./package.json
            echo 'EOF' 
          } >> $GITHUB_OUTPUT

  deploy-desktop:
    name: 'Build and Deploy for Desktop'
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' && contains(github.repository, '/VD-') }}
    needs: get-info
    uses: ./.github/workflows/deploy-desktop.yml

  deploy-webapp:
    name: 'Build and Deploy for the Web'
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'web' }}
    needs: get-info
    uses: ./.github/workflows/deploy-web.yml

  update-docs:
    name: 'Update Docs on GH Pages'
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'dev' }}
    needs: get-info
    uses: ./.github/workflows/release-docs.yml

